name: Continuous integration
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions: read-all

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        uses: ./.github/actions/test
