name: Continuous testing
on:
  push:
    branches-ignore:
     - 'dependabot/**'
  pull_request:

permissions: read-all

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Install goss and dgoss
        uses: e1himself/goss-installation-action@v1.0.4
        with:
          # Goss release version to install
          version: 'v0.3.16'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: false
          tags: phanan/koel:test

      - name: Run goss tests on the image
        run: dgoss run phanan/koel:test
